// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type AppSession struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type Event struct {
	ID             uuid.UUID `json:"id"`
	WebsiteID      uuid.UUID `json:"website_id"`
	SessionID      uuid.UUID `json:"session_id"`
	VisitID        uuid.UUID `json:"visit_id"`
	EventType      int32     `json:"event_type"`
	EventName      *string   `json:"event_name"`
	URLPath        string    `json:"url_path"`
	URLQuery       *string   `json:"url_query"`
	ReferrerPath   *string   `json:"referrer_path"`
	ReferrerQuery  *string   `json:"referrer_query"`
	ReferrerDomain *string   `json:"referrer_domain"`
	PageTitle      *string   `json:"page_title"`
	Hostname       *string   `json:"hostname"`
	UTMSource      *string   `json:"utm_source"`
	UTMMedium      *string   `json:"utm_medium"`
	UTMCampaign    *string   `json:"utm_campaign"`
	UTMContent     *string   `json:"utm_content"`
	UTMTerm        *string   `json:"utm_term"`
	CreatedAt      time.Time `json:"created_at"`
}

type EventDatum struct {
	ID          uuid.UUID  `json:"id"`
	WebsiteID   uuid.UUID  `json:"website_id"`
	EventID     uuid.UUID  `json:"event_id"`
	DataKey     string     `json:"data_key"`
	StringValue *string    `json:"string_value"`
	NumberValue *float64   `json:"number_value"`
	DateValue   *time.Time `json:"date_value"`
	DataType    int32      `json:"data_type"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID `json:"id"`
	WebsiteID  uuid.UUID `json:"website_id"`
	Browser    *string   `json:"browser"`
	OS         *string   `json:"os"`
	Device     *string   `json:"device"`
	Screen     *string   `json:"screen"`
	Language   *string   `json:"language"`
	Country    *string   `json:"country"`
	Region     *string   `json:"region"`
	City       *string   `json:"city"`
	DistinctID *string   `json:"distinct_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Username     string     `json:"username"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type Website struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	Domain    *string    `json:"domain"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}
