// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
select count(*)::bigint from users where deleted_at is null
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
insert into users (id, username, password_hash)
values ($1::uuid, $2, $3)
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const createWebsite = `-- name: CreateWebsite :one
insert into websites (id, user_id, name, domain)
values ($1::uuid, $2::uuid, $3, nullif($4::text, ''))
returning id, name, coalesce(domain, '')::text as domain, created_at
`

type CreateWebsiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Domain string    `json:"domain"`
}

type CreateWebsiteRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (CreateWebsiteRow, error) {
	row := q.db.QueryRow(ctx, createWebsite,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Domain,
	)
	var i CreateWebsiteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :execrows
update websites
set deleted_at = now()
where id = $1::uuid and user_id = $2::uuid and deleted_at is null
`

type DeleteWebsiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebsite(ctx context.Context, arg DeleteWebsiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebsite, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventMetrics = `-- name: EventMetrics :many
select
	coalesce(nullif(case $1::text
		when 'path' then url_path
		when 'referrer' then referrer_domain
		when 'event' then event_name
		else ''
	end, ''), '(none)')::text as name,
	count(*)::bigint as views,
	count(distinct session_id)::bigint as visitors
from events
where website_id = $2::uuid
  and created_at between $3 and $4
  and event_type = $5
group by name
order by views desc
limit $6
`

type EventMetricsParams struct {
	Metric     string    `json:"metric"`
	WebsiteID  uuid.UUID `json:"website_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
	EventType  int32     `json:"event_type"`
	LimitCount int32     `json:"limit_count"`
}

type EventMetricsRow struct {
	Name     string `json:"name"`
	Views    int64  `json:"views"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) EventMetrics(ctx context.Context, arg EventMetricsParams) ([]EventMetricsRow, error) {
	rows, err := q.db.Query(ctx, eventMetrics,
		arg.Metric,
		arg.WebsiteID,
		arg.StartAt,
		arg.EndAt,
		arg.EventType,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMetricsRow
	for rows.Next() {
		var i EventMetricsRow
		if err := rows.Scan(&i.Name, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
select
	id,
	username,
	password_hash,
	created_at,
	updated_at,
	deleted_at
from users
where id = $1::uuid and deleted_at is null
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
	id,
	username,
	password_hash,
	created_at,
	updated_at,
	deleted_at
from users
where username = $1 and deleted_at is null
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebsite = `-- name: GetWebsite :one
select id, name, coalesce(domain, '')::text as domain, created_at
from websites
where id = $1::uuid and user_id = $2::uuid and deleted_at is null
`

type GetWebsiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWebsiteRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetWebsite(ctx context.Context, arg GetWebsiteParams) (GetWebsiteRow, error) {
	row := q.db.QueryRow(ctx, getWebsite, arg.ID, arg.UserID)
	var i GetWebsiteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getWebsiteForCollection = `-- name: GetWebsiteForCollection :one
select id, name, coalesce(domain, '')::text as domain, created_at
from websites
where id = $1::uuid and deleted_at is null
`

type GetWebsiteForCollectionRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetWebsiteForCollection(ctx context.Context, id uuid.UUID) (GetWebsiteForCollectionRow, error) {
	row := q.db.QueryRow(ctx, getWebsiteForCollection, id)
	var i GetWebsiteForCollectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
insert into events (
	id, website_id, session_id, visit_id, event_type, event_name, url_path, url_query,
	referrer_path, referrer_query, referrer_domain, page_title, hostname, utm_source, utm_medium,
	utm_campaign, utm_content, utm_term, created_at
)
values (
	$1::uuid, $2::uuid, $3::uuid,
	$4::uuid, $5, nullif($6::text, ''),
	$7, nullif($8::text, ''), nullif($9::text, ''),
	nullif($10::text, ''), nullif($11::text, ''),
	nullif($12::text, ''), nullif($13::text, ''), nullif($14::text, ''),
	nullif($15::text, ''), nullif($16::text, ''),
	nullif($17::text, ''), nullif($18::text, ''),
	$19
)
`

type InsertEventParams struct {
	ID             uuid.UUID `json:"id"`
	WebsiteID      uuid.UUID `json:"website_id"`
	SessionID      uuid.UUID `json:"session_id"`
	VisitID        uuid.UUID `json:"visit_id"`
	EventType      int32     `json:"event_type"`
	EventName      string    `json:"event_name"`
	UrlPath        string    `json:"url_path"`
	UrlQuery       string    `json:"url_query"`
	ReferrerPath   string    `json:"referrer_path"`
	ReferrerQuery  string    `json:"referrer_query"`
	ReferrerDomain string    `json:"referrer_domain"`
	PageTitle      string    `json:"page_title"`
	Hostname       string    `json:"hostname"`
	UtmSource      string    `json:"utm_source"`
	UtmMedium      string    `json:"utm_medium"`
	UtmCampaign    string    `json:"utm_campaign"`
	UtmContent     string    `json:"utm_content"`
	UtmTerm        string    `json:"utm_term"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.WebsiteID,
		arg.SessionID,
		arg.VisitID,
		arg.EventType,
		arg.EventName,
		arg.UrlPath,
		arg.UrlQuery,
		arg.ReferrerPath,
		arg.ReferrerQuery,
		arg.ReferrerDomain,
		arg.PageTitle,
		arg.Hostname,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmContent,
		arg.UtmTerm,
		arg.CreatedAt,
	)
	return err
}

const insertEventData = `-- name: InsertEventData :exec
insert into event_data (
	id, website_id, event_id, data_key, string_value, number_value, date_value, data_type, created_at
)
values (
	$1::uuid, $2::uuid, $3::uuid,
	$4, nullif($5::text, ''), $6,
	$7, $8, $9
)
`

type InsertEventDataParams struct {
	ID          uuid.UUID          `json:"id"`
	WebsiteID   uuid.UUID          `json:"website_id"`
	EventID     uuid.UUID          `json:"event_id"`
	DataKey     string             `json:"data_key"`
	StringValue string             `json:"string_value"`
	NumberValue pgtype.Float8      `json:"number_value"`
	DateValue   pgtype.Timestamptz `json:"date_value"`
	DataType    int32              `json:"data_type"`
	CreatedAt   time.Time          `json:"created_at"`
}

func (q *Queries) InsertEventData(ctx context.Context, arg InsertEventDataParams) error {
	_, err := q.db.Exec(ctx, insertEventData,
		arg.ID,
		arg.WebsiteID,
		arg.EventID,
		arg.DataKey,
		arg.StringValue,
		arg.NumberValue,
		arg.DateValue,
		arg.DataType,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions (
	id, website_id, browser, os, device, screen, language, country, region, city, distinct_id, created_at
)
values (
	$1::uuid, $2::uuid, nullif($3::text, ''),
	nullif($4::text, ''), nullif($5::text, ''), nullif($6::text, ''),
	nullif($7::text, ''), nullif($8::text, ''),
	nullif($9::text, ''), nullif($10::text, ''),
	nullif($11::text, ''), $12
)
on conflict (id) do nothing
`

type InsertSessionParams struct {
	ID         uuid.UUID `json:"id"`
	WebsiteID  uuid.UUID `json:"website_id"`
	Browser    string    `json:"browser"`
	Os         string    `json:"os"`
	Device     string    `json:"device"`
	Screen     string    `json:"screen"`
	Language   string    `json:"language"`
	Country    string    `json:"country"`
	Region     string    `json:"region"`
	City       string    `json:"city"`
	DistinctID string    `json:"distinct_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.WebsiteID,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.Screen,
		arg.Language,
		arg.Country,
		arg.Region,
		arg.City,
		arg.DistinctID,
		arg.CreatedAt,
	)
	return err
}

const listWebsites = `-- name: ListWebsites :many
select id, name, coalesce(domain, '')::text as domain, created_at
from websites
where user_id = $1::uuid and deleted_at is null
order by name
`

type ListWebsitesRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Domain    string    `json:"domain"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListWebsites(ctx context.Context, userID uuid.UUID) ([]ListWebsitesRow, error) {
	rows, err := q.db.Query(ctx, listWebsites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebsitesRow
	for rows.Next() {
		var i ListWebsitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageviews = `-- name: Pageviews :many
select
	date_trunc($1::text, created_at)::timestamptz as time,
	count(*)::bigint as views,
	count(distinct session_id)::bigint as visitors
from events
where website_id = $2::uuid
  and created_at between $3 and $4
  and event_type = $5
group by time
order by time
`

type PageviewsParams struct {
	Bucket            string    `json:"bucket"`
	WebsiteID         uuid.UUID `json:"website_id"`
	StartAt           time.Time `json:"start_at"`
	EndAt             time.Time `json:"end_at"`
	PageviewEventType int32     `json:"pageview_event_type"`
}

type PageviewsRow struct {
	Time     time.Time `json:"time"`
	Views    int64     `json:"views"`
	Visitors int64     `json:"visitors"`
}

func (q *Queries) Pageviews(ctx context.Context, arg PageviewsParams) ([]PageviewsRow, error) {
	rows, err := q.db.Query(ctx, pageviews,
		arg.Bucket,
		arg.WebsiteID,
		arg.StartAt,
		arg.EndAt,
		arg.PageviewEventType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageviewsRow
	for rows.Next() {
		var i PageviewsRow
		if err := rows.Scan(&i.Time, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionMetrics = `-- name: SessionMetrics :many
select
	coalesce(nullif(case $1::text
		when 'browser' then sessions.browser
		when 'os' then sessions.os
		when 'device' then sessions.device
		when 'country' then sessions.country
		else ''
	end, ''), '(none)')::text as name,
	count(*)::bigint as views,
	count(distinct events.session_id)::bigint as visitors
from events
join sessions on sessions.id = events.session_id and sessions.website_id = events.website_id
where events.website_id = $2::uuid
  and events.created_at between $3 and $4
  and events.event_type = $5
group by name
order by views desc
limit $6
`

type SessionMetricsParams struct {
	Metric     string    `json:"metric"`
	WebsiteID  uuid.UUID `json:"website_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
	EventType  int32     `json:"event_type"`
	LimitCount int32     `json:"limit_count"`
}

type SessionMetricsRow struct {
	Name     string `json:"name"`
	Views    int64  `json:"views"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) SessionMetrics(ctx context.Context, arg SessionMetricsParams) ([]SessionMetricsRow, error) {
	rows, err := q.db.Query(ctx, sessionMetrics,
		arg.Metric,
		arg.WebsiteID,
		arg.StartAt,
		arg.EndAt,
		arg.EventType,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionMetricsRow
	for rows.Next() {
		var i SessionMetricsRow
		if err := rows.Scan(&i.Name, &i.Views, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebsite = `-- name: UpdateWebsite :execrows
update websites
set name = $1, domain = nullif($2::text, ''), updated_at = now()
where id = $3::uuid and user_id = $4::uuid and deleted_at is null
`

type UpdateWebsiteParams struct {
	Name   string    `json:"name"`
	Domain string    `json:"domain"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateWebsite(ctx context.Context, arg UpdateWebsiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebsite,
		arg.Name,
		arg.Domain,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const websiteStats = `-- name: WebsiteStats :one
with visits as (
	select
		visit_id,
		min(session_id::text) as session_id,
		count(*) as pageviews,
		min(created_at) as min_time,
		max(created_at) as max_time
	from events
	where website_id = $1::uuid
	  and created_at between $2 and $3
	  and event_type = $4
	group by visit_id
)
select
	coalesce(sum(pageviews), 0)::bigint as pageviews,
	count(distinct session_id)::bigint as visitors,
	count(*)::bigint as visits,
	count(*) filter (where pageviews = 1)::bigint as bounces,
	coalesce(sum(extract(epoch from (max_time - min_time))), 0)::bigint as total_time
from visits
`

type WebsiteStatsParams struct {
	WebsiteID         uuid.UUID `json:"website_id"`
	StartAt           time.Time `json:"start_at"`
	EndAt             time.Time `json:"end_at"`
	PageviewEventType int32     `json:"pageview_event_type"`
}

type WebsiteStatsRow struct {
	Pageviews int64 `json:"pageviews"`
	Visitors  int64 `json:"visitors"`
	Visits    int64 `json:"visits"`
	Bounces   int64 `json:"bounces"`
	TotalTime int64 `json:"total_time"`
}

func (q *Queries) WebsiteStats(ctx context.Context, arg WebsiteStatsParams) (WebsiteStatsRow, error) {
	row := q.db.QueryRow(ctx, websiteStats,
		arg.WebsiteID,
		arg.StartAt,
		arg.EndAt,
		arg.PageviewEventType,
	)
	var i WebsiteStatsRow
	err := row.Scan(
		&i.Pageviews,
		&i.Visitors,
		&i.Visits,
		&i.Bounces,
		&i.TotalTime,
	)
	return i, err
}
