// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSession struct {
	// 令牌
	Token string `json:"token"`
	// 数据
	Data []byte `json:"data"`
	// 过期时间
	Expiry time.Time `json:"expiry"`
}

type Event struct {
	// ID
	ID uuid.UUID `json:"id"`
	// 网站
	WebsiteID uuid.UUID `json:"website_id"`
	// 会话
	SessionID uuid.UUID `json:"session_id"`
	// 访问
	VisitID uuid.UUID `json:"visit_id"`
	// 类型
	EventType int32 `json:"event_type"`
	// 事件名
	EventName pgtype.Text `json:"event_name"`
	// 路径
	UrlPath string `json:"url_path"`
	// 查询参数
	UrlQuery pgtype.Text `json:"url_query"`
	// 来源路径
	ReferrerPath pgtype.Text `json:"referrer_path"`
	// 来源参数
	ReferrerQuery pgtype.Text `json:"referrer_query"`
	// 来源域名
	ReferrerDomain pgtype.Text `json:"referrer_domain"`
	// 页面标题
	PageTitle pgtype.Text `json:"page_title"`
	// 主机名
	Hostname pgtype.Text `json:"hostname"`
	// UTM 来源
	UtmSource pgtype.Text `json:"utm_source"`
	// UTM 媒介
	UtmMedium pgtype.Text `json:"utm_medium"`
	// UTM 活动
	UtmCampaign pgtype.Text `json:"utm_campaign"`
	// UTM 内容
	UtmContent pgtype.Text `json:"utm_content"`
	// UTM 关键词
	UtmTerm pgtype.Text `json:"utm_term"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type EventDatum struct {
	// ID
	ID uuid.UUID `json:"id"`
	// 网站
	WebsiteID uuid.UUID `json:"website_id"`
	// 事件
	EventID uuid.UUID `json:"event_id"`
	// 键
	DataKey string `json:"data_key"`
	// 字符串值
	StringValue pgtype.Text `json:"string_value"`
	// 数值
	NumberValue pgtype.Numeric `json:"number_value"`
	// 日期值
	DateValue pgtype.Timestamptz `json:"date_value"`
	// 数据类型
	DataType int32 `json:"data_type"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	// ID
	ID uuid.UUID `json:"id"`
	// 网站
	WebsiteID uuid.UUID `json:"website_id"`
	// 浏览器
	Browser pgtype.Text `json:"browser"`
	// 操作系统
	Os pgtype.Text `json:"os"`
	// 设备
	Device pgtype.Text `json:"device"`
	// 屏幕
	Screen pgtype.Text `json:"screen"`
	// 语言
	Language pgtype.Text `json:"language"`
	// 国家
	Country pgtype.Text `json:"country"`
	// 地区
	Region pgtype.Text `json:"region"`
	// 城市
	City pgtype.Text `json:"city"`
	// 访客标识
	DistinctID pgtype.Text `json:"distinct_id"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	// ID
	ID uuid.UUID `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 密码哈希
	PasswordHash string `json:"password_hash"`
	// 头像
	LogoUrl pgtype.Text `json:"logo_url"`
	// 显示名
	DisplayName pgtype.Text `json:"display_name"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Website struct {
	// ID
	ID uuid.UUID `json:"id"`
	// 用户
	UserID uuid.UUID `json:"user_id"`
	// 名称
	Name string `json:"name"`
	// 域名
	Domain pgtype.Text `json:"domain"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 删除时间
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
