// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSession struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type Event struct {
	ID             uuid.UUID   `json:"id"`
	WebsiteID      uuid.UUID   `json:"website_id"`
	SessionID      uuid.UUID   `json:"session_id"`
	VisitID        uuid.UUID   `json:"visit_id"`
	EventType      int32       `json:"event_type"`
	EventName      pgtype.Text `json:"event_name"`
	UrlPath        string      `json:"url_path"`
	UrlQuery       pgtype.Text `json:"url_query"`
	ReferrerPath   pgtype.Text `json:"referrer_path"`
	ReferrerQuery  pgtype.Text `json:"referrer_query"`
	ReferrerDomain pgtype.Text `json:"referrer_domain"`
	PageTitle      pgtype.Text `json:"page_title"`
	Hostname       pgtype.Text `json:"hostname"`
	UtmSource      pgtype.Text `json:"utm_source"`
	UtmMedium      pgtype.Text `json:"utm_medium"`
	UtmCampaign    pgtype.Text `json:"utm_campaign"`
	UtmContent     pgtype.Text `json:"utm_content"`
	UtmTerm        pgtype.Text `json:"utm_term"`
	CreatedAt      time.Time   `json:"created_at"`
}

type EventDatum struct {
	ID          uuid.UUID          `json:"id"`
	WebsiteID   uuid.UUID          `json:"website_id"`
	EventID     uuid.UUID          `json:"event_id"`
	DataKey     string             `json:"data_key"`
	StringValue pgtype.Text        `json:"string_value"`
	NumberValue pgtype.Numeric     `json:"number_value"`
	DateValue   pgtype.Timestamptz `json:"date_value"`
	DataType    int32              `json:"data_type"`
	CreatedAt   time.Time          `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID   `json:"id"`
	WebsiteID  uuid.UUID   `json:"website_id"`
	Browser    pgtype.Text `json:"browser"`
	Os         pgtype.Text `json:"os"`
	Device     pgtype.Text `json:"device"`
	Screen     pgtype.Text `json:"screen"`
	Language   pgtype.Text `json:"language"`
	Country    pgtype.Text `json:"country"`
	Region     pgtype.Text `json:"region"`
	City       pgtype.Text `json:"city"`
	DistinctID pgtype.Text `json:"distinct_id"`
	CreatedAt  time.Time   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Website struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Domain    pgtype.Text        `json:"domain"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
