/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/collect": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 采集事件 */
    post: operations["collect"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 登录 */
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 退出登录 */
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取当前用户 */
    get: operations["getCurrentUser"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 列出站点 */
    get: operations["listWebsites"]
    put?: never
    /** 创建站点 */
    post: operations["createWebsite"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取站点 */
    get: operations["getWebsite"]
    put?: never
    post?: never
    /** 删除站点 */
    delete: operations["deleteWebsite"]
    options?: never
    head?: never
    /** 更新站点 */
    patch: operations["updateWebsite"]
    trace?: never
  }
  "/api/websites/{websiteID}/metrics": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取站点指标 */
    get: operations["websiteMetrics"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}/pageviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取页面浏览趋势 */
    get: operations["websitePageviews"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}/stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 获取站点统计 */
    get: operations["websiteStats"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CollectPayload: {
      data?: {
        [key: string]: unknown
      }
      distinctId?: string
      language?: string
      name?: string
      referrer?: string
      screen?: string
      title?: string
      url: string
      /** Format: uuid */
      website: string
    }
    CollectRequest: {
      payload: components["schemas"]["CollectPayload"]
      /** @enum {string} */
      type?: "event"
    }
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string
      /** @description Error message text */
      message?: string
      /** @description The value at the given location */
      value?: unknown
    }
    ErrorModel: {
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string
      /** @description Optional list of individual error details */
      errors?: components["schemas"]["ErrorDetail"][] | null
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    LoginRequest: {
      password: string
      username: string
    }
    LoginResponse: {
      user: components["schemas"]["User"]
    }
    MetricRow: {
      name: string
      /** Format: int64 */
      views: number
      /** Format: int64 */
      visitors: number
    }
    OK: {
      ok: boolean
    }
    PageviewPoint: {
      label: string
      /** Format: date-time */
      time: string
      /** Format: int64 */
      views: number
      /** Format: int64 */
      visitors: number
    }
    User: {
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      deletedAt?: string
      /** Format: uuid */
      id: string
      /** Format: date-time */
      updatedAt?: string
      username: string
    }
    Website: {
      /** Format: date-time */
      createdAt: string
      domain: string
      /** Format: uuid */
      id: string
      name: string
    }
    WebsiteRequest: {
      domain?: string
      name: string
    }
    WebsiteStats: {
      /** Format: int64 */
      avgVisitSeconds: number
      /** Format: int64 */
      bounces: number
      /** Format: int64 */
      pageviews: number
      /** Format: int64 */
      totalTime: number
      /** Format: int64 */
      visitors: number
      /** Format: int64 */
      visits: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  collect: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CollectRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OK"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LoginResponse"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OK"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  getCurrentUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  listWebsites: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"][] | null
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  createWebsite: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteRequest"]
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  getWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  deleteWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["OK"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  updateWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websiteMetrics: {
    parameters: {
      query: {
        startAt?: number
        endAt?: number
        type: "path" | "referrer" | "browser" | "os" | "device" | "country" | "event"
        limit?: number
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MetricRow"][] | null
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websitePageviews: {
    parameters: {
      query?: {
        startAt?: number
        endAt?: number
        unit?: "hour" | "day" | "month"
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PageviewPoint"][] | null
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websiteStats: {
    parameters: {
      query?: {
        startAt?: number
        endAt?: number
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WebsiteStats"]
        }
      }
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
}
