/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/collect": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["collect"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getCurrentUser"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["listWebsites"]
    put?: never
    post: operations["createWebsite"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getWebsite"]
    put?: never
    post?: never
    delete: operations["deleteWebsite"]
    options?: never
    head?: never
    patch: operations["updateWebsite"]
    trace?: never
  }
  "/api/websites/{websiteID}/metrics": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["websiteMetrics"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}/pageviews": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["websitePageviews"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/websites/{websiteID}/stats": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["websiteStats"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    CollectPayload: {
      data?: {
        [key: string]: unknown
      }
      distinctId?: string
      language?: string
      name?: string
      referrer?: string
      screen?: string
      title?: string
      url: string
      /** Format: uuid */
      website: string
    }
    CollectRequest: {
      payload: components["schemas"]["CollectPayload"]
      /** @enum {string} */
      type?: "event"
    }
    ErrorDetail: {
      /** @description 错误发生位置，例如 body.items[3].tags 或 path.thing-id。 */
      location?: string
      /** @description 错误消息。 */
      message?: string
      /** @description 触发错误的值。 */
      value?: unknown
    }
    ErrorModel: {
      /**
       * @description 本次错误的具体说明。
       * @example 字段 foo 为必填项。
       */
      detail?: string
      /** @description 字段级错误详情列表。 */
      errors?: components["schemas"]["ErrorDetail"][] | null
      /**
       * Format: uri
       * @description 本次错误实例的标识地址。
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP 状态码。
       * @example 400
       */
      status?: number
      /**
       * @description 错误类型摘要。
       * @example 请求错误
       */
      title?: string
      /**
       * Format: uri
       * @description 错误类型文档地址。
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    EventOK: {
      ok: boolean
    }
    LoginRequest: {
      password: string
      username: string
    }
    LoginResponse: {
      user: components["schemas"]["User"]
    }
    MetricRow: {
      name: string
      /** Format: int64 */
      views: number
      /** Format: int64 */
      visitors: number
    }
    PageviewPoint: {
      label: string
      /** Format: date-time */
      time: string
      /** Format: int64 */
      views: number
      /** Format: int64 */
      visitors: number
    }
    User: {
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      deletedAt?: string
      /** Format: uuid */
      id: string
      /** Format: date-time */
      updatedAt?: string
      username: string
    }
    UserOK: {
      ok: boolean
    }
    Website: {
      /** Format: date-time */
      createdAt: string
      domain: string
      /** Format: uuid */
      id: string
      name: string
    }
    WebsiteOK: {
      ok: boolean
    }
    WebsiteRequest: {
      domain?: string
      name: string
    }
    WebsiteStats: {
      /** Format: int64 */
      avgVisitSeconds: number
      /** Format: int64 */
      bounces: number
      /** Format: int64 */
      pageviews: number
      /** Format: int64 */
      totalTime: number
      /** Format: int64 */
      visitors: number
      /** Format: int64 */
      visits: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  collect: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CollectRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EventOK"]
        }
      }
      /** @description 请求错误 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LoginResponse"]
        }
      }
      /** @description 请求错误 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UserOK"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  getCurrentUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  listWebsites: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"][] | null
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  createWebsite: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteRequest"]
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description 请求错误 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  getWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  deleteWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WebsiteOK"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  updateWebsite: {
    parameters: {
      query?: never
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["WebsiteRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Website"]
        }
      }
      /** @description 请求错误 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websiteMetrics: {
    parameters: {
      query: {
        startAt?: number
        endAt?: number
        type: "path" | "referrer" | "browser" | "os" | "device" | "country" | "event"
        limit?: number
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MetricRow"][] | null
        }
      }
      /** @description 请求错误 */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websitePageviews: {
    parameters: {
      query?: {
        startAt?: number
        endAt?: number
        unit?: "hour" | "day" | "month"
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PageviewPoint"][] | null
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
  websiteStats: {
    parameters: {
      query?: {
        startAt?: number
        endAt?: number
      }
      header?: never
      path: {
        websiteID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["WebsiteStats"]
        }
      }
      /** @description 未授权 */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 未找到 */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 请求参数无法处理 */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
      /** @description 服务器内部错误 */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/problem+json": components["schemas"]["ErrorModel"]
        }
      }
    }
  }
}
